version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout

      - setup_remote_docker:
          version: 18.06.0-ce

      - run:
          name: Set Environment Variables
          command: |
            echo 'export TAG=${CIRCLE_SHA1}' >> $BASH_ENV
            echo 'export IMAGE_NAME="reactweb"' >> $BASH_ENV
            echo 'export DOCKER_ID=${CIRCLE_USERNAME}'>> $BASH_ENV
            echo "Env Variable is set"
      - run:
          name: Build and push Docker image
          command: |
            docker build -t $CIRCLE_USERNAME/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $CIRCLE_USERNAME/$IMAGE_NAME:$TAG
workflows:
    build-and-test:
      jobs:
        - build-and-test