apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reactweb
  name: reactweb
  namespace: default
spec:
  selector:
    matchLabels:
      app: reactweb
  template:
    metadata:
      labels:
        app: reactweb
    spec:
      containers:
      - image: premsvmm/reactweb:323ddd533d49e882854e5bcb90a8e4da2f9a2892
        imagePullPolicy: IfNotPresent
        name: reactweb
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
